<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, 
									initial-scale=1.0" />
	<title>500 Error</title>
	<link href=
"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
		rel="stylesheet" />
	<style>
		body,
		html {
			height: 100%;
		}
	</style>
</head>

<body class="d-flex justify-content-top 
				align-items-top">
	<div class="col-md-12 text-center">
		<h1>500</h1>
		<h2>Server Error</h2>
		<p>
            The server encountered an internal error or misconfiguration 
            and was unable to complete your request.
		</p>
        <!--<a href="http://localhost:8000/">
			Go to Home
		</a>-->
	</div>
</body>

</html>